/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Update } from "./Update";
import { UpdateCountArgs } from "./UpdateCountArgs";
import { UpdateFindManyArgs } from "./UpdateFindManyArgs";
import { UpdateFindUniqueArgs } from "./UpdateFindUniqueArgs";
import { DeleteUpdateArgs } from "./DeleteUpdateArgs";
import { UpdateService } from "../update.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Update)
export class UpdateResolverBase {
  constructor(
    protected readonly service: UpdateService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Update",
    action: "read",
    possession: "any",
  })
  async _updatesMeta(
    @graphql.Args() args: UpdateCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Update])
  @nestAccessControl.UseRoles({
    resource: "Update",
    action: "read",
    possession: "any",
  })
  async updates(@graphql.Args() args: UpdateFindManyArgs): Promise<Update[]> {
    return this.service.updates(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Update, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Update",
    action: "read",
    possession: "own",
  })
  async update(
    @graphql.Args() args: UpdateFindUniqueArgs
  ): Promise<Update | null> {
    const result = await this.service.update(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Update)
  @nestAccessControl.UseRoles({
    resource: "Update",
    action: "delete",
    possession: "any",
  })
  async deleteUpdate(
    @graphql.Args() args: DeleteUpdateArgs
  ): Promise<Update | null> {
    try {
      return await this.service.deleteUpdate(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
